# Generated by Django 5.0.6 on 2024-08-29 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_channel_server_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='server_icon',
            new_name='icon',
        ),
    ]
